# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------
# Place your favicon.ico to /source directory.
favicon: /images/myimages/favicon.ico

# keywords
keywords: "Java, Python, Linux, Web, Canux, CHENG"

# Specify the date when the site was setup
since: 2013



# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
# When running hexo in a subdirectory (e.g. domain.tld/blog)
# Remove leading slashes ( "/archives" -> "archives" )
menu:
  home: /
  about: /about
  categories: /categories
  tags: /tags
  archives: /archives
  #commonweal: /404.html

# Enable/Disable menu icons.
# Icon Mapping:
#   Map a menu item to a specific FontAwesome icon name.
#   Key is the name of menu item and value is the name of FontAwsome icon.
#   When an question mask icon presenting up means that the item has no mapping icon.
menu_icons:
  enable: true
  # Icon Mapping.
  home: home
  about: user
  categories: th
  tags: tags
  archives: archive
  #commonweal: heartbeat



# ---------------------------------------------------------------
# Scheme Settings
# ---------------------------------------------------------------
# Schemes
scheme: Muse
#scheme: Mist
#scheme: Pisces



# ---------------------------------------------------------------
# Donate Settings
# ---------------------------------------------------------------
reward_comment: 您的支持是我创作的动力!
wechatpay: /images/myimages/wechatpay.jpg
alipay: /images/myimages/alipay.jpg



# ---------------------------------------------------------------
# Sidebar Settings
# ---------------------------------------------------------------
# Social links
social:
  GitHub: https://github.com/crazy-canux
  Stackoverflow: http://stackoverflow.com/
  LinkedIn: http://www.linkedin.com/profile/preview?locale=zh_CN&trk=prof-0-sb-preview-primary-button
  E-mail: mailto:canuxcheng@gmail.com

# Social Icons
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  LinkedIn: linkedin
  stackoverflow: stack-overflow
  E-mail: envelope

# Links
links_title: Links
links:
  CSDN: http://bbs.csdn.net/home
  51CTO: http://bbs.51cto.com/
  ChinaUnix: http://bbs.chinaunix.net/
  ITPUB: http://www.itpub.net/forum.php

# Sidebar Avatar
# in theme directory(source/images): /images/avatar.jpg
# in site  directory(source/uploads): /uploads/avatar.jpg
# default : /images/default_avatar.jpg
avatar: /images/myimages/avatar.jpg

# TOC in the Sidebar
toc:
  enable: true
  # Automatically add list number to toc.
  number: true

# Creative Commons 4.0 International License.
# http://creativecommons.org/
# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: zero

sidebar:
  # Sidebar Position, available value: left | right
  position: left
  #position: right

  # Sidebar Display, available value:
  #  - post    expand on posts automatically. Default.
  #  - always  expand for all pages automatically
  #  - hide    expand only when click on the sidebar toggle icon.
  #  - remove  Totally remove sidebar including sidebar toggle icon.
  display: post
  #display: always
  #display: hide
  #display: remove



# ---------------------------------------------------------------
# Misc Theme Settings
# ---------------------------------------------------------------
# Custom Logo.
# !!Only available for Default Scheme currently.
# Options:
#   enabled: [true/false] - Replace with specific image
#   image: url-of-image   - Images's url
custom_logo:
  enabled: false
  image:

# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night eighties

# Automatically scroll page to section which is under <!-- more --> mark.
scroll_to_more: true

# Automatically Excerpt
auto_excerpt:
  enable: true
  length: 150

# Use Lato font
use_font_lato: true



# ---------------------------------------------------------------
# Third Party Services Settings
# ---------------------------------------------------------------
# MathJax Support
mathjax: true

#------------analytics and count-----------
# Facebook sdk Analytics
facebook_sdk:
  enable: false
  app_id: #<app_id>
  fb_admin: #<user_id>
  like_button: #true
  webmaster: #true

# leancloud Analytics
leancloud_visitors:
  enable: false
  app_id: #<app_id>
  app_key: #<app_key>

# Google Analytics - US
#google_analytics:

# ibruce Analytics - CN

# CNZZ  - CN
cnzz_siteid: 1258132457

# Baidu Analytics ID
#baidu_analytics: 8343378

# Tencent analytics ID
#tencent_analytics: 55134199

#------------comment system-----------------
# Disqus - US
#disqus_shortname: canux

# Duoshuo - CN
duoshuo_shortname: crazy-canux
# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id:
  #admin_nickname: ROOT
# Make duoshuo show hot artical
duoshuo_hotartical: true

#------------share-------------------------
# AddThis - US
#add_this_id:

# JiaThis - CN
jiathis: true

# Baidu Share
#baidushare: true
# Available value:
#    button | slide
#type: button

# Duoshuo Share
#duoshuo_share: true

#------------search-----------------------
# Swiftype - US
swiftype_key: xGAKY5LyK8xDYvH9zzcX

# Tinysou - CN
#tinysou_Key

#------------SEO-----------------------
# Webluker



#! ---------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! ---------------------------------------------------------------
# Motion
use_motion: true

# Fancybox
fancybox: true

# Static files
vendors: vendors
css: css
js: js
images: images

# Theme version
version: 0.5.0
